import crypto from "crypto";
import fs from "fs/promises";
import path from "path";
import multer from "multer";
import cloudinary from "../config/Cloudinary";
import type { IRecordAttachment } from "../Models/MedicalRecord";
import { logger } from "../Utils/logger";
import { ServiceError } from "./errors";

// Private storage for medical documents (lab results, scans, discharge
// papers) uploaded by hospital staff.
//
// - cloudinary: uploaded as "authenticated" raw files, so they have no public
//   URL. The API fetches them with a signed, one-minute download link and
//   streams them to the signed-in user who may see them.
// - local: files on the server's disk (RECORD_FILES_DIR, default ./uploads).
//   For development and tests only: Render's disk is wiped on every deploy.
//
// STORAGE_DRIVER picks one; by default Cloudinary when it's configured.

export const DOCUMENT_MAX_BYTES = 10 * 1024 * 1024;

// The types we accept, each with the bytes its files start with. The type is
// checked from the content, not the file name or the browser's claim.
const SIGNATURES: { contentType: string; extension: string; magic: number[] }[] = [
  { contentType: "application/pdf", extension: "pdf", magic: [0x25, 0x50, 0x44, 0x46] }, // %PDF
  { contentType: "image/jpeg", extension: "jpg", magic: [0xff, 0xd8, 0xff] },
  { contentType: "image/png", extension: "png", magic: [0x89, 0x50, 0x4e, 0x47] },
];

export const documentUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: DOCUMENT_MAX_BYTES, files: 1 },
});

export function detectDocumentType(buffer: Buffer) {
  const match = SIGNATURES.find((s) => s.magic.every((byte, i) => buffer[i] === byte));
  if (!match) throw new ServiceError(400, "Upload a PDF, JPG or PNG file", "file");
  return match;
}

type Driver = IRecordAttachment["provider"];

function driver(): Driver {
  const chosen = process.env.STORAGE_DRIVER;
  if (chosen === "local" || chosen === "cloudinary") return chosen;
  return process.env.CLOUD_NAME && process.env.CLOUDINARY_API_KEY ? "cloudinary" : "local";
}

const localDir = () => path.resolve(process.env.RECORD_FILES_DIR || "uploads");

if (driver() === "local" && process.env.NODE_ENV === "production") {
  logger.warn("Medical documents are stored on local disk in production; they will be lost on redeploy. Configure Cloudinary.");
}

export async function saveDocument(buffer: Buffer, originalName: string): Promise<IRecordAttachment> {
  const type = detectDocumentType(buffer);
  const id = crypto.randomUUID();
  const base = { contentType: type.contentType, bytes: buffer.length, originalName: originalName.slice(0, 200) };

  if (driver() === "cloudinary") {
    const publicId = await new Promise<string>((resolve, reject) => {
      const stream = cloudinary.uploader.upload_stream(
        { resource_type: "raw", type: "authenticated", folder: "MediBridge/records", public_id: `${id}.${type.extension}` },
        (error, result) => (error || !result ? reject(error ?? new Error("Upload failed")) : resolve(result.public_id))
      );
      stream.end(buffer);
    });
    return { provider: "cloudinary", key: publicId, ...base };
  }

  const key = `${id}.${type.extension}`;
  await fs.mkdir(localDir(), { recursive: true });
  await fs.writeFile(path.join(localDir(), key), buffer);
  return { provider: "local", key, ...base };
}

export async function readDocument(attachment: IRecordAttachment): Promise<Buffer> {
  if (attachment.provider === "cloudinary") {
    const url = cloudinary.utils.private_download_url(attachment.key, "", {
      resource_type: "raw",
      type: "authenticated",
      expires_at: Math.floor(Date.now() / 1000) + 60,
    });
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Document download failed with status ${response.status}`);
    return Buffer.from(await response.arrayBuffer());
  }
  // Keys are generated by us, but never let one point outside the folder.
  return fs.readFile(path.join(localDir(), path.basename(attachment.key)));
}

export async function deleteDocument(attachment: IRecordAttachment) {
  try {
    if (attachment.provider === "cloudinary") {
      await cloudinary.uploader.destroy(attachment.key, { resource_type: "raw", type: "authenticated", invalidate: true });
    } else {
      await fs.unlink(path.join(localDir(), path.basename(attachment.key)));
    }
  } catch (err) {
    logger.warn({ err, key: attachment.key }, "Could not delete a medical document file");
  }
}

// "Lipid panel.pdf": a safe download name from the record title.
export const downloadName = (title: string, contentType: string) =>
  `${title.replace(/[^\w-]+/g, "-").replace(/-+/g, "-")}.${SIGNATURES.find((s) => s.contentType === contentType)?.extension ?? "bin"}`;
